### ISSUE TITLE
side effect in constructor

### ISSUE THREAD

**Issue by myname1614** [akbarjoudi/yii2-bot-telegram#18]
after click button like this:

![image](https://user-images.githubusercontent.com/34938365/79599175-bb86ce80-80ed-11ea-8439-e17f6dcd6995.png)

I receive json in webhook action like this:
`{"update_id":35392806,"callback_query":{"id":"841781883300197","from":{"id":43869442,"is_bot":false,"first_name":"firstname","last_name":"lastname","language_code":"xx"},"message":{"message_id":85,"from":{"id":11389716,"is_bot":true,"first_name":"bot-name","username":"botname_bot"},"chat":{"id":4384420,"first_name":"firstname","last_name":"lastname","type":"private"},"date":1587144909,"text":"ttttttttttttttttt","reply_markup":{"inline_keyboard":[[{"text":"button1","callback_data":"[\"clickButton1\",{\"result\":\"clickButton1!\"}]"},{"text":"button2","callback_data":"[\"clickButton2\",{\"result\":\"clickButton2!\"}]"},{"text":"button3","callback_data":"[\"clickButton3\",{\"result\":\"clickButton3!\"}]"}]]}},"chat_instance":"-12738114497231891","data":"[\"clickButton1\",{\"result\":\"clickButton1!\"}]"}}
`

After this, I retrieve component $telegram = Yii::$app->telegram;
It cause problem:

`2020-04-17 20:33:38[-][me7hu4bsfma1s6mhr7dogorgf5][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: aki\telegram\base\Input::callback_query in /.../vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /.../vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set()
#1 /.../vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#2 /.../vendor/aki/yii2-bot-telegram/base/TelegramBase.php(45): yii\base\BaseObject->__construct()
#3 [internal function]: aki\telegram\base\TelegramBase->__construct()
#4 /.../vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs()
#5 /.../vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build()
#6 /.../vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#7 /.../vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()
#8 /.../vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get()
#9 /.../vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get()
#10 /.../common/components/Telegram/WebhookProcessor.php(34): yii\di\ServiceLocator->__get()`

> 

If I will to override constructor in my component:
class Telegram extends \aki\telegram\Telegram
without to call parent constructor, 
this to broke initialisation yii\base\Component

**Comment by myname1614** [comment]
perhaps this should be optional
`        $input = file_get_contents("php://input");
        $array= json_decode($input, true);
        $this->input = new Input($array);
`

**Comment by jfkz** [comment]
I didnt use the latest rewritten version of this component, but when I check the code, I realized that moving data reading to init() isnt bad idea.
Cant test it right now, but, probably @myname1614 can you create pull request with your idea?

I also use suggest to use `Yii::$app->request->getRawBody()` instead of accessing to `php://input` directly, in case that this component is hardly tied with Yii2.

Btw, thanks for good job, @akbarjoudi, keep it moving!

**Comment by myname1614** [comment]
I removed this component from my project.
It’s easier to write a new component than to suffer with someone else’s

**Comment by akbarjoudi** [comment]
Dear friend, this bug was fixed
