### ISSUE TITLE
aki\telegram\base\Input::callback_query 

### ISSUE THREAD

**Issue by VladimirusK** [akbarjoudi/yii2-bot-telegram#19]
Dear, Akbar!

I have some problem with callback_query and receive the error when I try to click inline button: yii\base\UnknownPropertyException: Setting unknown property: aki\telegram\base\Input::callback_query 

Can you help me, how I can solve this problem?

Hope for your help.

**Comment by akbarjoudi** [comment]
Hi.
I will definitely check this issue and let you know

**Comment by akbarjoudi** [comment]
Dear friend, this bug was fixed
