### ISSUE TITLE
sendPhoto bug

### ISSUE THREAD

**Issue by Elgorm** [akbarjoudi/yii2-bot-telegram#22]
Photo is being sent, but I get an error.

PHP Warning 'yii\base\ErrorException' with message 'Invalid argument supplied for foreach()'

![image](https://user-images.githubusercontent.com/8758619/100604992-1261b100-3329-11eb-92f9-84c775b9f365.png)

**Comment by akbarjoudi** [comment]
Please send your code here

**Comment by akbarjoudi** [comment]
hi @Elgorm 
I tested the codes and found no problems.
You can use this code.

```php
$root = Yii::getAlias("@webroot");
Yii::$app->telegram->sendPhoto([
    'chat_id' => $telegram->input->message->chat->id,
    'photo' => $root.'/images/cast.jpg',
    'caption' => 'this is test'
]);
```

**Comment by Elgorm** [comment]
Maybe because I do not use id, but use the nickname of the channel?

**Comment by akbarjoudi** [comment]
No, not for the reason you said. I updated the library, please try again after installing the update library.

**Comment by c7v** [comment]
Возможно ошибки как-то связаны #35
