### ISSUE TITLE
Missing all_members_are_administrators on Chat.php

### ISSUE THREAD

**Issue by macklus** [akbarjoudi/yii2-bot-telegram#24]
Hi,
i start using yii2-bot-telegram today, and, after send a message, it throws en Exception because try to fill all_members_are_administrators on types/Chat.php, and there not defined on it.

I suppouse that this variable were added recently.

Problem was solved by adding:
```
public $all_members_are_administrators;
```

on this file

**Comment by akbarjoudi** [comment]
hi @macklus 
I did not see this feature in the Telegram documentation that you mentioned. Please tell me what conditions this feature was sent to you.
Please refer to the link below

https://core.telegram.org/bots/api#chat

**Comment by macklus** [comment]
As telegram reference on their API:
https://core.telegram.org/bots/api-changelog

The field all_members_are_administrators has been removed from the documentation for the Chat object. The field is still returned in the object for backward compatibility, but new bots should use the permissions field instead.

so, yes, this variable are neccesary.
I understood that problem dont appears before because no one uses a group with all admins

**Comment by akbarjoudi** [comment]
Dear friend @macklus 

You are right and according to the reasons you said, then this feature must be added. Thankful

**Comment by macklus** [comment]
Thanks, problem solved
