### ISSUE TITLE
Setting unknown property: aki\telegram\base\Input::id

### ISSUE THREAD

**Issue by oleg4646** [akbarjoudi/yii2-bot-telegram#26]
Hello. I tried send a few fhotos and get error in second iteration.
Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Setting unknown property: aki\telegram\base\Input::id' 
`foreach ($post['Images'] as $image) {
                        Yii::$app->telegram->sendPhoto([
                            'chat_id' => $chatId,
                            'photo' => $webroot . $image,
                            'caption' => 'this is test'
                        ]);
                    }`

**Comment by oleg46** [comment]
after update package, error fixed
How i can send photos as album?

**Comment by akbarjoudi** [comment]
Hi dear friend @oleg46 
This feature does not currently exist, but I will definitely add this feature soon.
This will probably be fixed tomorrow

**Comment by oleg46** [comment]
Thank you very much. I'll wait)

**Comment by akbarjoudi** [comment]
Dear friend @oleg46 
you can use albums in developer mode. But it needs to be tested again

using 
```php
composer require aki/yii2-bot-telegram dev-master
```

**Comment by oleg46** [comment]
I set in my composer.json 
```
"aki/yii2-bot-telegram": "dev-master"
```
in code
```
use aki\telegram\types\InputMedia\InputMediaPhoto;

if (isset($post['Images']) && !empty($post['Images'])) {
                    $webroot = Yii::getAlias("@webroot");

                    $photoArr = [];
                    foreach ($post['Images'] as $image) {

                        $photoArr[] =  new InputMediaPhoto([
                            'type' => 'photo',
                            'media' => $webroot . $image,
                            //'caption'=>"aa"
                        ]);

                    }

                    Yii::$app->telegram->sendMediaGroup([
                        'chat_id' => $chatId,
                        'media' => $photoArr
                    ]);
                }
```
and get error 
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: aki\telegram\Telegram::sendMediaGroup()'

**Comment by akbarjoudi** [comment]
@oleg46 
You have given the path here but you have to send the image address

**Comment by oleg46** [comment]
Diar friend. I set media param to 
```
'media' => Url::home(true) . $image,
```
but it doen`t meather to find method. Method sendMediaGroup() still not found.

**Comment by akbarjoudi** [comment]
I did not understand what you meant. But use the code I sent in the comment above is correct. Please test the following code as well.

```php
'media' => Url::home('https') .'/images/'. $image,// https://nulled-scripts.ir/images/logo.png
```

**Comment by oleg46** [comment]
Yes, i mean what picture available in Url::home(true) . $image. This code formed url to picture.  Like in your example. But when i call Yii::$app->telegram->sendMediaGroup i get error Calling unknown method: aki\telegram\Telegram::sendMediaGroup() and this method not present in class Telegram in your package.

**Comment by akbarjoudi** [comment]
oops!

Sorry for the function I created not pushed. Now you can test again by updating the package.
