### ISSUE TITLE
Setting unknown property: aki\telegram\types\Result::caption_entities

### ISSUE THREAD

**Issue by dmitriymikheev** [akbarjoudi/yii2-bot-telegram#28]
Hi. I tried send a photo and get an error:
Setting unknown property: aki\telegram\types\Result::caption_entities

It happens when markdown style used in caption.

Example request:
```php
Yii::$app->telegram->sendPhoto([
            'chat_id' => '@channel',
            'photo' => 'link',
            'caption' => '*test_caption*'.PHP_EOL.'More info: https://google.com',
            'parse_mode' => 'markdown',
        ]);
```

Photo is successfully sent to the channel.

**Comment by akbarjoudi** [comment]
Hi dear friend. This bug was fixed.
