### ISSUE TITLE
Invalid param - getUserProfilePhotos - chat_id

### ISSUE THREAD

**Issue by PitBult** [akbarjoudi/yii2-bot-telegram#3]
Hi!

Invalid url: _getUserProfilePhotos?chat_id=********_

`{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: user not found"
}`

Valid url: _https://api.telegram.org/bot[token]/getUserProfilePhotos?user_id=[chat_id]_

You must change parameter from **chat_id** to **user_id**.

**Comment by akbarjoudi** [comment]
oops. The new version was fixed
