### ISSUE TITLE
Setting unknown property: aki\telegram\types\InlineKeyboard::url

### ISSUE THREAD

**Issue by tdavenger** [akbarjoudi/yii2-bot-telegram#30]
Hi. I have updated the telegram bot and found this error each time I try to call Inline keyboard. 

```
$keyboard = array(
                        array(
                            array('text'=>'Перейти','url'=>$model->link),
                        )
                    );

        $tg = Yii::$app->telegram->sendMessage([
            'chat_id' => Test::TEST_CHAT_TELEGRAM,
            'text' => 'test',
            'parse_mode' => 'html',
            'reply_markup' => json_encode(array('inline_keyboard' => $keyboard))
            ]);
```

the message sends in the telegram channel with the button, but I can't get any data from the reply.

`model->created_on = $tg->result->date; // recieves null. `

I tried to use new InlineKeyboardMarkup Class, but it is not working (no buttons displayed). Maybe I did something wrong?

**Comment by pashara** [comment]
https://github.com/akbarjoudi/yii2-bot-telegram/pull/33

**Comment by akbarjoudi** [comment]
Hello dear friends, this problem has been solved
