### ISSUE TITLE
getChat method problem

### ISSUE THREAD

**Issue by vladisa123** [akbarjoudi/yii2-bot-telegram#34]
Just use the simple code according the example, but have some problems
Can you help me, how to solve it?
<img width="1280" alt="Снимок экрана 2021-04-08 в 16 59 43" src="https://user-images.githubusercontent.com/47428311/114040528-60b12e80-988c-11eb-9ede-0525f3cdb4ae.png">

**Comment by vladisa123** [comment]
I fix it, don’t know is it right or not, but it works)
in file base/result line 40, change $this->_result = new Result($value); to $this->_result = $value;

and it will work fine

**Comment by c7v** [comment]
Я добавил в aki\telegram\types\Result

```php
   public $id;
   public $first_name;
   public $last_name;
   public $username;
   public $type;
   public $bio;
```

Но вылетает ошибка:
PHP Warning – yii\base\ErrorException
Invalid argument supplied for foreach()

Пока не разбирался, времени нет.

>I fix it, don’t know is it right or not, but it works)
>in file base/result line 40, change $this->_result = new Result($value); to $this->_result = $value;
it works :)

**Comment by akbarjoudi** [comment]
@c7v Hello dear friend, in what state are these features set?

**Comment by vladisa123** [comment]
Самый простой Варик, чтобы получить массив и работать с ним, который я нашёл, это в файле телеграмм вообще не использовать Response, а работать только с body

**Comment by c7v** [comment]
> @c7v Hello dear friend, in what state are these features set?
Hello friend, sorry, I did not understand your question.

**Comment by akbarjoudi** [comment]
@c7v My dear friend, when I start the Response Robot, I do not receive these properties that you mentioned.

I want to know how you got this property in response.
Or, as you say, maybe the structure of the telegram answer has changed, in which case I should check

**Comment by akbarjoudi** [comment]
@c7v  Thanks, I will fix it as soon as possible

**Comment by c7v** [comment]
Fixed already? Thank you 👍🏼

**Comment by akbarjoudi** [comment]
@c7v  Yes dear friend version 3.0.7 has been released. Please update to fix the bug
