### ISSUE TITLE
Setting unknown property: aki\telegram\types\Sticker::emoji

### ISSUE THREAD

**Issue by meh0709** [akbarjoudi/yii2-bot-telegram#46]
Yii::$app->telegram->sendSticker([
            'chat_id' => **********,
            'sticker' => 'CAACAgIAAxkBAAMXYXqYNUAra0z3XY8HG7_uWfSNsYIAAiACAALxBJcTR_sYaCfFWXMhBA',
        ]);

**Comment by c7v** [comment]
Hey! Well, does the problem persist?

**Comment by c7v** [comment]
@akbarjoudi I think we can close this issues.

**Comment by akbarjoudi** [comment]
@c7v thanks
