### ISSUE TITLE
PhpDoc for TelegramBase::send()

### ISSUE THREAD

**Issue by 4erk** [akbarjoudi/yii2-bot-telegram#48]
method return Array but in PhpDoc said that return string

**Comment by c7v** [comment]
Hi! Check [/base/TelegramBase.php](https://github.com/akbarjoudi/yii2-bot-telegram/blob/master/base/TelegramBase.php#L126) line 126

**Comment by c7v** [comment]
@akbarjoudi I think we can close this issues.
