### ISSUE TITLE
Need add param "clientConfig" for Guzzle/Client

### ISSUE THREAD

**Issue by 4erk** [akbarjoudi/yii2-bot-telegram#49]
For example, I needed to specify the parameter 'verify' => false

**Comment by 4erk** [comment]
In component need property for configure guzzle client

**Comment by c7v** [comment]
Why do you need it? The task is interesting and useful, but the question of whether this is appropriate.

**Comment by c7v** [comment]
@akbarjoudi I think we can close this issues.
