### ISSUE TITLE
Error - Result::reply_to_message

### ISSUE THREAD

**Issue by kzpromo** [akbarjoudi/yii2-bot-telegram#51]
hello, when i try reply to message
i recive error message

Setting unknown property: aki\telegram\types\Result::reply_to_message

my code

```
Yii::$app->telegram->sendMessage([
'chat_id' => $this->user->chat_id,
'reply_to_message_id' => $this->msg_id,
'text' => $this->answer,
]);
```

**Comment by mihaly487** [comment]
A similar error, only for a different parameter aki\telegram\types\Result :: has_protected_content for method editMessageText

**Comment by cept73** [comment]
Update it. At this moment, all might work "from the box"

**Comment by cept73** [comment]
> hello, when i try reply to message i recive error message
> 
> Setting unknown property: aki\telegram\types\Result::reply_to_message
> 
> my code
> 
> ```
> Yii::$app->telegram->sendMessage([
> 'chat_id' => $this->user->chat_id,
> 'reply_to_message_id' => $this->msg_id,
> 'text' => $this->answer,
> ]);
> ```

Check it to close the issue
