### ISSUE TITLE
error TelegramBase:129 

### ISSUE THREAD

**Issue by sinelnikof** [akbarjoudi/yii2-bot-telegram#56]
hi! in php8.0 error 

    aki\telegram\base\TelegramBase:129
    
    public function send(string $method, ?array $params = null): array
must be 
    public function send(string $method, ?array $params = array()): array

**Comment by c7v** [comment]
Hi @sinelnikof 

I'll see what I can do. If I fix it, I'll post it.

**Comment by c7v** [comment]
Can you send part of your code where you use this method?

**Comment by akbarjoudi** [comment]
It was temporarily fixed

**Comment by c7v** [comment]
@akbarjoudi Hi, why did you remove the typing? What was the problem?

**Comment by akbarjoudi** [comment]
@c7v Hi, because the type of output it gives is not always array type

**Comment by c7v** [comment]
> @c7v Hi, because the type of output it gives is not always array type

Hello, here you go, a typed language 😃
