### ISSUE TITLE
Error if message contains a link

### ISSUE THREAD

**Issue by oleg4646** [akbarjoudi/yii2-bot-telegram#60]
`Yii::$app->telegram->sendMessage([
       'chat_id' => '123',
       'text' => self::getTelegrammMessage($order, true),
  ]);`
after message sent got error
**Setting unknown property: aki\telegram\types\Result::link_preview_options**

**Comment by MaksTrader** [comment]
Hi. I have the same problem if message contains a link.
But. I don't get this error every time. I don't understand the system of its occurrence yet.
Did you manage to solve this problem or create some solution of your own?

**Comment by oleg4646** [comment]
I resolved this issue by adding this property to aki\telegram\types\Result 
`public $link_preview_options`;

**Comment by egorrishe** [comment]
Pull request #61 is fixing it.
