### ISSUE TITLE
In types/Result.php some properties are missing. Please add them!

### ISSUE THREAD

**Issue by dany-hub** [akbarjoudi/yii2-bot-telegram#62]
In typys/Result.php follow properties are missing. Please add them.

public $message_thread_id;

   public $reply_to_message;

   public $link_preview_options;

   public $is_topic_message;

**Comment by dany-hub** [comment]
Can you please look at this issue please? Thanks!

**Comment by akbarjoudi** [comment]
@dany-hub The above items were added

Update your version

**Comment by dany-hub** [comment]
Thanks!!!
