### ISSUE TITLE
sendPhoto always returns 'null' in response

### ISSUE THREAD

**Issue by the0rist** [akbarjoudi/yii2-bot-telegram#7]
Everything is fine, but sendPhoto with body:
`[
    'chat_id' => <MY_CHAT_ID>,
    'photo' => <ANY_DIRECT_URL_TO_ANY_PHOTO>,
    'caption => <ANY_CAPTION>
]` always returns empty response.

Other methods (e.g. sendMessage) works well.

**Comment by akbarjoudi** [comment]
Give an example of your coding

**Comment by Eminbekov** [comment]
Same problem

**Comment by akbarjoudi** [comment]
Put your photo on the ./web cover
and run it

```php
<?php Yii::$app->telegram->sendPhoto([
	'chat_id' => $chat_id,
	'photo' => 'sample.jpg',
	'caption' => 'this is test'
]); ?>
```
Or you can do this with the address
Consider the following example
```php
<?php Yii::$app->telegram->sendPhoto([
	'chat_id' => $chat_id,
	'photo' => 'https://www.yiiframework.com/doc/guide/2.0/en/images/start-app-installed.png',
	'caption' => 'this is test'
]); ?>
```
Or you can with the file_id
Consider the following example
```php
<?php Yii::$app->telegram->sendPhoto([
	'chat_id' => $chat_id,
	'photo' => '221454525425',
	'caption' => 'this is test'
]); ?>
```
This document is a telegram and you can refer to it

https://core.telegram.org/bots/api#sendphoto
https://core.telegram.org/bots/api#inputfile

**Comment by Eminbekov** [comment]
Thank you for your answer, but nothing is working I tried everything but useless.
