### ISSUE TITLE
set web hook

### ISSUE THREAD

**Issue by paskuale75** [akbarjoudi/yii2-bot-telegram#8]
Can I get a url to this function as below ?
```
Yii::$app->telegram->setWebhook([
            'url' => Url::to(['//application/default/bot-reply-to-chat'],true)
        ])
```
...absolute url (https) to a controller action. Thanks

**Comment by akbarjoudi** [comment]
You have to do this

Yii::$app->telegram->setWebhook([
            'url' => Yii::$app->urlManager->createAbslouteUrl('controller/action')
        ])
